version: '3.8'

services:

  app: 
    build: 
      context: app
      target: builder
    networks:
      - web 
      - elk
    tty: true
    volumes:
      - ./app:/app
    command: sh -c "pnpm install && pnpm start"

  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
      ELASTIC_PASSWORD: local
      xpack.security.enrollment.enabled: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic/docker-cluster.log:/usr/share/elasticsearch/logs/docker-cluster.log
      - elasticsearchdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elk
    stdin_open: true

  logstash:
    image: logstash:8.12.2
    environment:
      # discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_INTERNAL_PASSWORD: local
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    build:
      context: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=local
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # - /var/run/docker.sock:/host_docker/docker.sock
      # - /var/lib/docker:/host_docker/var/lib/docker
      - filebeatdata:/usr/share/filebeat/data:rw
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
  web:  

volumes:
  elasticsearchdata:
  filebeatdata: 