version: '3.8'

services:
  app: 
    build: 
      context: app
      target: builder
    networks:
      - web 
      - elk
    tty: true
    user: root
    volumes:
      - ./app:/app
    depends_on:
      - elasticsearch
      - filebeat
    command: sh -c "pnpm install && pnpm cmd:crawler"

  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: local
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elk
    stdin_open: true

  logstash:
    image: logstash:8.12.2
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ls_data:/usr/share/logstash/data
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    build:
      context: filebeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - filebeat_data:/usr/share/filebeat/data:rw
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
      - filebeat
    networks:
      - elk

networks:
  elk:
    driver: bridge
  web:  

volumes:
  elasticsearch_data:
  filebeat_data:
  ls_data:
  kb_data: