filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.inputs:
- type: container
  enabled: true
  paths:
    - "/var/lib/docker/containers/*/*.log"

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

logging.json: true
logging.metric:
  enabled: true
  period: 10s

# output.logstash:
#   hosts: ["logstash:5044"]
#   ttl: 120

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "local"
  indices:
    - index: "app-%{+yyyy.MM.dd}"        
      when:
          equals:
            container.image.name: node-scraping-app  
          contains:
            

setup.kibana.host: "http://kibana:5601"
